### ISSUE TITLE
refactor gene creation

### ISSUE THREAD

**Issue by JulianNorton** [JulianNorton/genetic-algorithm#2]
Line 18

> just do gene += random.randint(0,1) and get rid of the whole if-else thing

**Comment by agoloprem** [comment]
Remember to convert the result of `randint(0, 1)` to str, though: http://stackoverflow.com/a/961638/4840376

``` python
gene += str(random.randint(0, 1))
```

**Comment by JulianNorton** [comment]
https://github.com/JulianNorton/genetic-algorithm/commit/bf670b3feb753bb5a213cf4d3d99bb11c82c5b0f

Done!
